In [3]:
import unittest

if __name__ == "__main__":
    loader = unittest.TestLoader()
    start_dir = "../tests"
    suite = loader.discover(start_dir)
    runner = unittest.TextTestRunner()
    runner.run(suite)

..
----------------------------------------------------------------------
Ran 2 tests in 0.437s

OK


In [1]:
import os
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
basedir = os.path.dirname(os.path.abspath(''))
sourcedir = os.path.join(basedir, 'source')
import sys
sys.path.insert(0, sourcedir)
from source.mcmc import MCMC

%config InlineBackend.figure_format = 'retina'
font = {'size'   : 16, 'family':'STIXGeneral'}
axislabelfontsize='large'
matplotlib.rc('font', **font)
matplotlib.mathtext.rcParams['legend.fontsize']='medium'
plt.rcParams["figure.figsize"] = [8.0,6.0]

datadir = os.path.join(basedir, 'data')

binned_data_file = os.path.join(datadir, 'lcparam_DS17f.txt')
binned_sys_file = os.path.join(datadir, 'sys_DS17f.txt')

    # The for loop is to allow for the option of plotting multiple chains on the same chart
    # (It just kinda looks cool)
print(f"Starting Markov Chain")
start = [np.random.uniform(0, 1), np.random.uniform(0,1), np.random.uniform(50,100), np.random.uniform(-25, -15)]
    #start = [.25, .74, 68]
g_cov_test = np.diag([.01, .01, .1, .01])
markov_chain = MCMC(initial_state=start,
                    data_file=binned_data_file,
                    systematics_file=binned_sys_file,
                    g_cov=g_cov_test)

markov_chain.make_chain(1000)

print(markov_chain.chain)

starting tests


E
ERROR: test_compare_cosmomodel_vs_astropy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_compare_cosmomodel_vs_astropy
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/rhensley/Documents/classes/phys_250/250_project_group_2/unittests/test_compare_cosmomodel_vs_astropy.py", line 12, in <module>
    CosmoModel = cm.CosmoModel
AttributeError: partially initialized module 'source.cosmo_model' has no attribute 'CosmoModel' (most likely due to a circular import)


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


Starting Markov Chain
[[  0.7359582    0.62728516  64.65902696 -18.1660676 ]
 [  0.64267028   0.54288953  64.50919372 -18.0462853 ]
 [  0.68134961   0.79865898  64.57775405 -18.21424404]
 ...
 [  0.36640343   0.65156853  67.24549531 -19.51849292]
 [  0.225956     0.57142307  67.52280018 -19.56586922]
 [  0.19084447   0.76252775  67.86453188 -19.5925964 ]]


In [1]:
fig, ax = plt.subplots(4,1)

ax[0].plot(markov_chain.Omega_m)
ax[1].plot(markov_chain.Omega_L)
ax[2].plot(markov_chain.H0)
ax[3].plot(markov_chain.M)
plt.show()

NameError: name 'plt' is not defined

In [ ]:
x = markov_chain.chain
print(x, type(x))
print(x.T, type(x.T))
cov = np.cov(markov_chain.chain.T)
alpha= .1
cov*=alpha
print(cov)

In [ ]:
start = [np.random.uniform(0, 1), np.random.uniform(0,1), np.random.uniform(50,100), np.random.uniform(-25, -15)]
    #start = [.25, .74, 68]
markov_chain2 = MCMC(initial_state=start,
                    data_file=binned_data_file,
                    systematics_file=binned_sys_file, 
                    g_cov=cov)

markov_chain2.make_chain(10000)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_40586/2006045694.py", line 8, in <cell line: 8>
    markov_chain2.make_chain(10000)
  File "/home/rhensley/Documents/classes/phys_250/250_project_group_2/source/mcmc.py", line 166, in make_chain
    self.propagate_chain()
  File "/home/rhensley/Documents/classes/phys_250/250_project_group_2/source/mcmc.py", line 151, in propagate_chain
    acceptance_prob, new_log_likelihood = self.generate_acceptance_prob(self._current_state, candidate_state)
  File "/home/rhensley/Documents/classes/phys_250/250_project_group_2/source/mcmc.py", line 137, in generate_acceptance_prob
    new_log_likelihood = self.log_likelihood(candidate_state)
  File "/home/rhensley/Documents/classes/phys_250/250_project_group_2/source/mcmc.py", line 67, in log_likelihood
    mu_vector = (self._mb - params

In [ ]:
fig, ax = plt.subplots(4,1)
ax[0].plot(markov_chain.Omega_m)
ax[1].plot(markov_chain.Omega_L)
ax[2].plot(markov_chain.H0)
ax[3].plot(markov_chain.M)
plt.show()

In [ ]:
plt.hist2d(markov_chain2.chain[500:,0], markov_chain2.chain[500:,1], bins=(50, 50), cmap=plt.cm.jet)
plt.show()